[2023-06-10T01:07:25.654+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: taxi_zone_data_dag.download_dataset_task scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10T01:07:25.673+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: taxi_zone_data_dag.download_dataset_task scheduled__2023-06-09T00:00:00+00:00 [queued]>
[2023-06-10T01:07:25.677+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-06-10T01:07:25.677+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-06-10T01:07:25.678+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-06-10T01:07:25.693+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): download_dataset_task> on 2023-06-09 00:00:00+00:00
[2023-06-10T01:07:25.702+0000] {standard_task_runner.py:54} INFO - Started process 420 to run task
[2023-06-10T01:07:25.709+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'taxi_zone_data_dag', 'download_dataset_task', 'scheduled__2023-06-09T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_multiFile_v02.py', '--cfg-path', '/tmp/tmpaanui1tv']
[2023-06-10T01:07:25.710+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask download_dataset_task
[2023-06-10T01:07:25.712+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/data_ingestion_gcs_multiFile_v02.py
[2023-06-10T01:07:25.827+0000] {data_ingestion_gcs_multiFile_v02.py:20} INFO - dtc_data_lake_dtc-dezc-001 is the bucket.
[2023-06-10T01:07:25.847+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-06-10T01:07:25.902+0000] {task_command.py:384} INFO - Running <TaskInstance: taxi_zone_data_dag.download_dataset_task scheduled__2023-06-09T00:00:00+00:00 [running]> on host f41d61956f54
[2023-06-10T01:07:25.952+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=taxi_zone_data_dag
AIRFLOW_CTX_TASK_ID=download_dataset_task
AIRFLOW_CTX_EXECUTION_DATE=2023-06-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-06-09T00:00:00+00:00
[2023-06-10T01:07:25.953+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-06-10T01:07:25.954+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sSLf https://github.com/DataTalksClub/nyc-tlc-data/releases/tag/misctaxi_zone_lookup.csv > /opt/***/taxi_zone_lookup.csv']
[2023-06-10T01:07:25.964+0000] {subprocess.py:86} INFO - Output:
[2023-06-10T01:07:26.262+0000] {subprocess.py:93} INFO - curl: (22) The requested URL returned error: 404
[2023-06-10T01:07:26.264+0000] {subprocess.py:97} INFO - Command exited with return code 22
[2023-06-10T01:07:26.276+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 22.
[2023-06-10T01:07:26.278+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=taxi_zone_data_dag, task_id=download_dataset_task, execution_date=20230609T000000, start_date=20230610T010725, end_date=20230610T010726
[2023-06-10T01:07:26.286+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task download_dataset_task (Bash command failed. The command returned a non-zero exit code 22.; 420)
[2023-06-10T01:07:26.330+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-06-10T01:07:26.399+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
